#!/usr/bin/env ruby
# encoding: UTF-8

require File.expand_path(
            File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'delayed/command'
Delayed::Command.new(ARGV).daemonize
