#!/bin/bash

set -e

rake spec

git push

# wait for travis build to start
set +e
SLEPT_FOR=0
until travis status | grep start; do
  sleep 5
  SLEPT_FOR=$((SLEPT_FOR + 5))
  if [ $SLEPT_FOR -ge 120 ]; then exit 1; fi
done

# wait for travis to pass
SLEPT_FOR=0
until travis status --fail-pending --no-exit-code; do
  sleep 10
  SLEPT_FOR=$((SLEPT_FOR + 10))
  if [ $SLEPT_FOR -ge 600 ]; then exit 1; fi
done
set -e

# exit the script if the build failed
travis status --exit-code

# merge to deploy
git checkout deploy
git merge master
git push
git checkout master

# wait for docker container build

# build AMI
# cd aws
# packer build packer.json

# deploy new AMI
# ./deploy.sh ami
