#!/bin/bash

export NPROC=`nproc`
NUM_DELAYED_JOB_WORKERS=$((NPROC - 1))
NUM_DELAYED_JOB_WORKERS=$((
  NUM_DELAYED_JOB_WORKERS > 0 ? NUM_DELAYED_JOB_WORKERS : 1
  ))
export NUM_DELAYED_JOB_WORKERS

# give the application 2G and rest of the machine's memory to varnish
TOTAL_MEMORY_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
VARNISH_MEMORY_KB=$((TOTAL_MEMORY_KB - 2000000))
VARNISH_MEMORY=$((
  VARNISH_MEMORY_KB < 268435 ? 256 : VARNISH_MEMORY_KB / 1048
  ))
export VARNISH_STORAGE=malloc,${VARNISH_MEMORY}M

erb /app/docker/monitrc.erb > /app/docker/monitrc

chmod 0700 /app/docker/monitrc

exec /usr/local/bin/monit -I -v -c /app/docker/monitrc
